---
- name: Create /root/bin path
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [ 02-bin-utils ]

- name: Create /root/src path
  file:
    path: /root/src
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [ 02-bin-utils ]

- name: Clean previous ztp sources
  file:
    path: /root/src/ztp
    state: absent
  tags: [ 02-bin-utils ]

- name: Download ztp repo
  git:
    repo: https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable.git
    dest: /root/src/ztp
  tags: [ 02-bin-utils ]

- name: Build set-motd binary
  command: 
    cmd: go build -o /root/bin/set-motd
    chdir: /root/src/ztp/hack/set-motd
    creates: /root/bin/set-motd
  tags: [ 02-bin-utils ]

- name: Create set-motd disclaimer
  copy:
    dest: /etc/motd.d/set-motd
    owner: root
    group: root
    mode: "0755"
    content: |
      
      Set or unset current server's status:
      set-motd set [-user] [-motd] [-pr]
      set-motd unset
      
  tags: [ 02-bin-utils ]
